/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service health, including seed status */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the synthetic instrument universe */
        get: operations["listInstruments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{symbol}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily OHLCV history for one instrument */
        get: operations["getPrices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{symbol}/fundamentals/concepts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One instrument's fundamentals catalog
         * @description One entry per (concept, provider, unit) group stored for the instrument, with fact count and filed_at range. Raw XBRL facts the ingest did not map onto a canonical concept (empty `concept`) are excluded: this catalog names the concepts a series can be requested for. Concepts marked `derived` (e.g. `short_volume_ratio` = finra short_volume / total_volume) are computed at read time from stored concepts, never stored themselves. Empty on the synthetic demo dataset, which holds no fundamentals.
         */
        get: operations["listInstrumentFundamentalConcepts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{symbol}/fundamentals/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One instrument's fundamental concept as a point-in-time series
         * @description Three transforms over the concept's facts:
         *
         *       * `raw` -- the point-in-time as-of series: one point per filing
         *         date, each carrying the value knowable on that date (filed_at <=
         *         date, latest filing wins). Per-holder filings (FCA short
         *         positions) are summed across holders per date, each holder's
         *         latest filing persisting until they file again. With `start_date`,
         *         an opening point at `start_date` carries the value knowable as of
         *         that date, so a windowed read does not start from the first filing
         *         inside the window.
         *       * `raw_facts` -- the facts exactly as filed, ascending by filed_at,
         *         with both dates on every row.
         *       * `yoy_growth` -- year-over-year change of the as-of series; the
         *         base is the as-of value one year earlier (a step lookup, not a
         *         calendar guess), and points without a base are dropped.
         *
         *     `start_date`/`end_date` filter on `filed_at`, never `period_end`: asking for a window asks "what was knowable between these dates". Every response carries `point_in_time: true` and a `provenance` string stating exactly how the numbers were produced.
         */
        get: operations["getFundamentalSeries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List signals with filtering, sorting, and total count
         * @description `total` always reflects the full result set under the active filters, independent of pagination, so the UI count can be checked against the backend (SC-004).
         */
        get: operations["listSignals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catalog of registered signal models, discovered at runtime
         * @description Enumerates every model currently registered in the backend plugin registry, with its declared parameter metadata (Constitution II). Registering a model MUST make it appear here with no change to this document's consumers.
         */
        get: operations["listModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recorded runs, newest first */
        get: operations["listRuns"];
        put?: never;
        /**
         * Run a model over a dataset selection
         * @description Validates the requested parameters against the model's declared metadata, resolves a warm-up window of the model's lookback_days before start_date, executes, and returns the completed run. Signals dated outside [start_date, end_date] are computed for warm-up but not reported. Execution is synchronous; see research.md for the scaling boundary this implies.
         *     An optional `execution` object records user-settable execution criteria (capital, sizing, costs, stops, fill timing) with the run. The criteria do not change the signals; they change how the run's performance report turns those signals into fills, so they are stored as provenance and echoed back on the run.
         *     The model is selected by `model_name` (a registry builtin) or `custom_rule_id` (one of the caller's rules from POST /rules) -- exactly one of the two. A custom rule's config is fixed at definition time, so `parameters` overrides cannot combine with `custom_rule_id`.
         */
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        /** One run with its provenance, summary, and produced signals */
        get: operations["getRun"];
        put?: never;
        post?: never;
        /** Delete a run and the signals it produced */
        delete: operations["deleteRun"];
        options?: never;
        head?: never;
        /** Name a run to keep it as a saved experiment */
        patch: operations["saveRun"];
        trace?: never;
    };
    "/runs/{run_id}/performance": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        /**
         * Equity curve, benchmark, trades and risk metrics for one run
         * @description Derived from the run's own signals and the bars inside its window, and computed here because the frontend must not embed analytical computation (Constitution V). Recomputed on request rather than stored: every input is already persisted, so a cached copy could only go stale.
         *     Not a tradeable backtest. `assumptions` lists every simplification applied and ships inside the payload, so the caveat travels with the numbers rather than living in UI copy that a refactor can drop.
         */
        get: operations["getRunPerformance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/replay/stream": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        /**
         * Replay a run's window as a server-sent event stream
         * @description Streams the run's window chronologically, as if history were arriving live: each trading date's bars, the stored signals firing that date, the fills the simulator executes at that date's close, and one end-of-date equity mark, ending with a summary event. The body is a sequence of `data: {json}\n\n` frames; every frame's JSON object carries an `event` field, one of:
         *
         *       * `bar` -- `{date, closes}`: the date's close per run symbol. Thinned
         *         to every `step`-th date; a date carrying a signal always gets one.
         *       * `signal` -- `{date, symbol, direction, trigger_values,
         *         data_window_end}`: a stored signal as it fires.
         *       * `fill` -- `{date, symbol, side, qty, price, value,
         *         realized_pnl}`: an executed trade at the close of the signal date.
         *       * `equity` -- `{date, equity, cash, positions, realized_pnl}`: the
         *         book marked once per replayed date, after that date's fills.
         *       * `summary` -- terminal; the ReplaySummary object.
         *       * `truncated` -- terminal in place of `summary` when `max_events`
         *         cut the stream short: `{event, detail}`.
         *
         *     Events on one date arrive in bar, signal, fill, equity order, so a signal never precedes the bar event of its own date. Sizing and filling mirror the run's performance report exactly (equal-weight per-symbol sleeves, close-of-signal-date fills, no costs): the terminal `summary` reconciles with GET /runs/{run_id}/performance.
         */
        get: operations["streamRunReplay"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/replay/summary": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        /**
         * The replay engine run to completion, as one object
         * @description Drives the same engine as the stream endpoint to completion and returns only its terminal summary event. Useful for clients that do not want SSE, and the cheapest way to check a replay reconciles with GET /runs/{run_id}/performance.
         */
        get: operations["getRunReplaySummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/replay/live/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Replay a Kafka bar stream live, as a server-sent event stream
         * @description The streaming counterpart of GET /runs/{run_id}/replay/stream. A publisher (`quantlab replay-publish`) has turned a warehouse window into a chronological bar stream on the Kafka replay topic; this endpoint consumes the topic from the beginning, re-runs the model's compute on each symbol's growing window as bars arrive (identical to batch by the point-in-time truncation guarantee), and trades the new signals through the same portfolio simulator.
         *     The frame format is exactly the batch replay's: `bar`, `signal`, `fill`, `equity` and a terminal `summary` (whose `run_id` is `live:<model>`), plus `truncated` if `max_events` cuts the stream short. Bars dated before `start` act as warm-up: they feed the model's lookback but emit no events and no trades, mirroring how a batch run loads history before its window. Because of that warm-up, the terminal summary reconciles with a batch replay of a run over the same model, symbols and window when the publisher's range covers the model's lookback before `start`.
         *     Requires the streaming stack (`docker compose --profile streaming up`). A 503 means the bus is unconfigured (QUANTLAB_KAFKA_BROKERS unset) or the broker is unreachable -- never a startup failure.
         */
        get: operations["streamLiveReplay"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/signal-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catalog of signal templates custom rules are built from
         * @description Templates, not expressions: a custom rule is a template id plus a config whose fields come from the fixed enums in `config_fields`. `inputs` declares what the template reads ("bars"; "bars+fundamentals" arrives later), and `available_on_dataset` reports whether the active dataset can serve it -- fundamental templates report false on the SQLite demo. Registry-driven: a new template appears here with no change to consumers.
         */
        get: operations["listSignalTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's custom rules */
        get: operations["listCustomRules"];
        put?: never;
        /** Define a custom signal rule from a template */
        post: operations["createCustomRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        /** One custom rule */
        get: operations["getCustomRule"];
        put?: never;
        post?: never;
        /**
         * Delete a rule
         * @description Runs that used the rule stay readable (their definition snapshot is recorded on the run) and report model_available=false.
         */
        delete: operations["deleteCustomRule"];
        options?: never;
        head?: never;
        /**
         * Rename a rule or replace its config
         * @description The template is immutable: changing what a rule IS makes a new rule. Runs that already used the rule keep their definition snapshot; edits apply to future runs only.
         */
        patch: operations["updateCustomRule"];
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a user
         * @description Public only while no users exist; that first user is created with `is_admin: true`. Once any user exists, registration requires an admin's session cookie and new users are created non-admin.
         */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in, receiving the session cookie
         * @description On success sets the `quantlab_session` cookie (HttpOnly, SameSite=Lax; Secure only when QUANTLAB_AUTH_COOKIE_SECURE is set, since local development is plain http). Failed attempts are rate limited per client IP.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out, revoking the session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The authenticated user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Which store answered. `sqlite` is the synthetic demo dataset; `warehouse` is real ingested history. Two runs from different datasets are never directly comparable.
         * @enum {string}
         */
        Dataset: "sqlite" | "warehouse";
        /** @description A split or dividend inside a run's window. Reported, never applied: stored bars are unadjusted, so a split makes the price series jump in a way that is an artefact rather than a market move. */
        CorporateActionNotice: {
            instrument_id: number;
            symbol: string;
            /** Format: date */
            ex_date: string;
            /** @enum {string} */
            action_type: "split" | "dividend";
            split_ratio?: number | null;
            dividend?: number | null;
        };
        Health: {
            /** @enum {string} */
            status: "ok";
            dataset: components["schemas"]["Dataset"];
            /** @description True once the seed step has completed */
            seeded: boolean;
            signal_count: number;
        };
        /** @enum {string} */
        Direction: "bullish" | "bearish";
        Instrument: {
            /** @example ZZTRND */
            symbol: string;
            /** @example Zeno Trend Industries (synthetic) */
            name: string;
            /** @example USD */
            currency: string;
            /**
             * @description `macro` labels the warehouse's BoE/FRED pseudo-instruments (a macro series loaded as daily bars). It labels, never filters: macro instruments are served like any other instrument.
             * @enum {string}
             */
            kind: "equity" | "macro";
            /** @enum {string} */
            regime_profile: "trending" | "mean_reverting" | "volatile" | "mixed";
        };
        InstrumentList: {
            total: number;
            items: components["schemas"]["Instrument"][];
        };
        PriceBar: {
            symbol: string;
            /** Format: date */
            date: string;
            open: number;
            high: number;
            low: number;
            close: number;
            volume: number;
        };
        PriceBarList: {
            total: number;
            items: components["schemas"]["PriceBar"][];
        };
        FundamentalConcept: {
            /** @example revenue */
            concept: string;
            /** @example sec_edgar */
            provider: string;
            /** @example USD */
            unit: string;
            fact_count: number;
            /** Format: date */
            first_filed: string;
            /** Format: date */
            last_filed: string;
            /** @description True for concepts computed at read time from stored ones (e.g. short_volume_ratio = finra short_volume / total_volume); derived concepts are never themselves stored. */
            derived: boolean;
        };
        FundamentalConceptList: {
            symbol: string;
            total: number;
            items: components["schemas"]["FundamentalConcept"][];
        };
        FundamentalFact: {
            value: number;
            /**
             * Format: date
             * @description Null for instantaneous (balance-sheet) facts.
             */
            period_start: string | null;
            /**
             * Format: date
             * @description The fiscal period the value describes. Never a visibility anchor.
             */
            period_end: string;
            /**
             * Format: date
             * @description When the market could first know this value. The point-in-time anchor: a fact is visible to a model only from filed_at onwards.
             */
            filed_at: string;
            /** @example sec_edgar */
            provider: string;
            /** @example USD */
            unit: string;
            /** @description Present on per-holder filings (FCA short positions). */
            holder: string | null;
        };
        FundamentalSeriesPoint: {
            /** Format: date */
            date: string;
            /** @description The value knowable on that date (the as-of step series). */
            value: number;
        };
        FundamentalSeries: {
            symbol: string;
            concept: string;
            /** @enum {string} */
            transform: "raw" | "raw_facts" | "yoy_growth";
            /** @description Always true: filed_at is the visibility axis on every transform. The flag ships so the UI never has to infer the discipline. */
            point_in_time: boolean;
            /** @description How the numbers were produced, stated with the numbers. */
            provenance: string;
            total: number;
            /** @description Series points for `raw`/`yoy_growth`; facts as filed for `raw_facts`. */
            items: (components["schemas"]["FundamentalSeriesPoint"] | components["schemas"]["FundamentalFact"])[];
        };
        Signal: {
            id: number;
            symbol: string;
            /**
             * Format: date
             * @description Signal date T; only data knowable by T was used
             */
            date: string;
            /** @example sma-crossover */
            rule_name: string;
            /** @example 1.0.0 */
            rule_version: string;
            /**
             * @example {
             *       "fast": 20,
             *       "slow": 50
             *     }
             */
            parameters: {
                [key: string]: unknown;
            };
            direction: components["schemas"]["Direction"];
            /**
             * @description Indicator values that fired the rule
             * @example {
             *       "sma_fast": 101.2,
             *       "sma_slow": 99.8
             *     }
             */
            trigger_values: {
                [key: string]: unknown;
            };
            /**
             * Format: date
             * @description Latest bar date used as input; always <= date (Constitution VII)
             */
            data_window_end: string;
        };
        SignalList: {
            /** @description Total signals matching the active filters (pre-pagination) */
            total: number;
            items: components["schemas"]["Signal"][];
        };
        Error: {
            detail: string;
        };
        AuthCredentials: {
            username: string;
            password: string;
        };
        User: {
            id: number;
            username: string;
            is_admin: boolean;
        };
        UserPublic: {
            id: number;
            username: string;
        };
        ParamSpec: {
            name: string;
            /** @enum {string} */
            type: "int" | "float" | "bool" | "enum";
            default: unknown;
            /** @description Inclusive lower bound; numeric types only. */
            minimum?: number | null;
            /** @description Inclusive upper bound; numeric types only. */
            maximum?: number | null;
            /** @description Permitted values; required when type is enum. */
            choices?: unknown[] | null;
            description?: string;
        };
        Model: {
            /** @example sma-crossover */
            name: string;
            /** @example 1.0.0 */
            version: string;
            parameters: components["schemas"]["ParamSpec"][];
            /** @description Bars of history the model needs before it can emit. */
            lookback_days: number;
            /** @enum {string} */
            scale_class: "scale_free" | "price_scaled";
            direction_semantics: string;
            /** @enum {string} */
            origin: "builtin" | "custom";
            /** @description Present for custom rules; use it as custom_rule_id on POST /runs. */
            custom_rule_id: string | null;
            /** @description The template a custom rule instantiates; null for builtins. */
            template: string | null;
        };
        ModelList: {
            total: number;
            items: components["schemas"]["Model"][];
        };
        RunRequest: {
            /** @description Registry builtin model. Exactly one of model_name and custom_rule_id is required. */
            model_name?: string;
            /** @description Omit to use the highest registered version. */
            model_version?: string;
            /** @description One of the caller's rules from POST /rules. Mutually exclusive with model_name; parameters overrides do not apply to custom rules (their config is fixed at definition time). */
            custom_rule_id?: string;
            /** @description Overrides only. Omitted parameters take the model's declared default; the merged result is recorded as the run's effective parameters. */
            parameters?: {
                [key: string]: unknown;
            };
            symbols: string[];
            /** Format: date */
            start_date: string;
            /** Format: date */
            end_date: string;
            execution?: components["schemas"]["ExecutionCriteria"];
        };
        /** @description The definition a custom-rule run actually executed, frozen at run time: template + config + derived lookback. Editing or deleting the rule afterwards never rewrites this. */
        CustomRuleSnapshot: {
            rule_id: string;
            name: string;
            slug: string;
            /** @example indicator-threshold */
            template: string;
            config: {
                [key: string]: unknown;
            };
            lookback_days: number;
        };
        CustomRuleRequest: {
            name: string;
            /** @description Template id from GET /signal-templates. */
            template: string;
            /** @description Validated against the template's declared vocabulary. */
            config: {
                [key: string]: unknown;
            };
        };
        /** @description At least one of name and config is required. */
        CustomRuleUpdateRequest: {
            name?: string;
            config?: {
                [key: string]: unknown;
            };
        };
        CustomRule: {
            rule_id: string;
            name: string;
            /** @description Derived from the name; unique within the owner's scope. */
            slug: string;
            template: string;
            config: {
                [key: string]: unknown;
            };
            /** @description Derived from the config, not declared. */
            lookback_days: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CustomRuleList: {
            total: number;
            items: components["schemas"]["CustomRule"][];
        };
        SignalTemplate: {
            /** @example indicator-threshold */
            id: string;
            /** @example 1.0.0 */
            version: string;
            description: string;
            /**
             * @description What the template reads.
             * @enum {string}
             */
            inputs: "bars" | "bars+fundamentals";
            /** @description Whether the active dataset can serve this template. Fundamental templates report false on the SQLite demo. */
            available_on_dataset: boolean;
            /** @description Enums and bounds per config field, for form generation. */
            config_fields: {
                [key: string]: unknown;
            };
        };
        SignalTemplateList: {
            total: number;
            items: components["schemas"]["SignalTemplate"][];
        };
        /** @description How a run's signals are turned into fills in its performance report. Every field defaults to the historical behaviour, so omitting the object entirely and supplying it with all defaults produce the same numbers: an equal-weight sleeve per selected instrument, filled at the close of the signal date, charged nothing, capped at nothing. */
        ExecutionCriteria: {
            /**
             * @description Starting book value.
             * @default 100000
             */
            initial_capital: number;
            /**
             * @description `equal_weight` splits initial_capital into one sleeve per selected instrument (an untraded sleeve sits in cash). `fixed_fraction` sizes each entry at `fraction` of the book's current value, drawn from one shared cash account.
             * @default equal_weight
             * @enum {string}
             */
            position_sizing: "equal_weight" | "fixed_fraction";
            /**
             * @description Share of the book's current value per entry; fixed_fraction only.
             * @default 0.1
             */
            fraction: number;
            /**
             * @description Cap on concurrently open positions; entries beyond the cap are skipped. Null means uncapped.
             * @default null
             */
            max_open_positions: number | null;
            /**
             * @description Charged on every fill, as basis points of traded value.
             * @default 0
             */
            transaction_cost_bps: number;
            /**
             * @description Charged on every fill, in currency units.
             * @default 0
             */
            fixed_cost_per_trade: number;
            /**
             * @description Exit when a bar's low trades this fraction below the entry price; filled at the stop level, or at the open when the market gaps through it. When a stop and a take-profit trigger on the same bar, the stop is assumed to fill first.
             * @default null
             */
            stop_loss_pct: number | null;
            /**
             * @description Exit when a bar's high trades this fraction above the entry price; filled at the target level, or at the open on a gap through it.
             * @default null
             */
            take_profit_pct: number | null;
            /**
             * @description `same_close` fills at the close of the signal date. `next_open` fills at the open of the next session that has a bar, removing the same-bar fill assumption.
             * @default same_close
             * @enum {string}
             */
            entry_price: "same_close" | "next_open";
        };
        RunCoverage: {
            instruments_requested: number;
            /** @description How many requested instruments had bars in the window. */
            instruments_with_data: number;
            /** @description How many had the model's full lookback before start_date. The remainder may under-report early in the window. */
            instruments_full_warmup: number;
        };
        Run: {
            id: string;
            /** @description Set when saved as a named experiment; null otherwise. */
            name?: string | null;
            model_name: string;
            model_version: string;
            /** @description Effective parameters (declared defaults merged with overrides). */
            parameters: {
                [key: string]: unknown;
            };
            symbols: string[];
            /** Format: date */
            start_date: string;
            /** Format: date */
            end_date: string;
            /** @enum {string} */
            status: "completed" | "failed";
            /** @description Present when status is failed. */
            error?: string | null;
            /** Format: date-time */
            created_at: string;
            /** @description Zero is a valid result, not a failure. */
            signal_count: number;
            coverage: components["schemas"]["RunCoverage"];
            dataset: components["schemas"]["Dataset"];
            /** @description Surrogate instrument identities actually run against. Present for warehouse runs, null on the demo. Recorded because the canonical symbol is unique but editable, while instrument_id is the stable key the bar store joins on. */
            instrument_ids?: number[] | null;
            /** @description The ingest runs behind the bars this run read. This is what makes a later re-ingest of the same window distinguishable from the original run, when every input the researcher chose is identical. */
            ingest_run_ids?: number[] | null;
            /** @description Actions overlapping the window for the selected instruments. Empty on the demo dataset, which has none. */
            corporate_actions?: components["schemas"]["CorporateActionNotice"][];
            /** @description The effective execution criteria the run was created with, merged over their defaults. Null for runs recorded without them; their performance uses the historical zero-cost measuring instrument. */
            execution?: components["schemas"]["ExecutionCriteria"];
            /** @description Set on runs of a custom rule: the definition snapshot. Null for builtin-model runs. */
            custom_rule?: components["schemas"]["CustomRuleSnapshot"];
            /** @description False when the run's recorded dataset is not the active one. The run stays readable; it simply cannot be reproduced as recorded. */
            re_runnable?: boolean;
            /** @description False when the recorded model/version is no longer registered; the run stays readable but is not re-runnable. */
            model_available?: boolean;
        };
        RunList: {
            total: number;
            items: components["schemas"]["Run"][];
        };
        ExperimentSignal: {
            symbol: string;
            /** Format: date */
            date: string;
            direction: components["schemas"]["Direction"];
            trigger_values: {
                [key: string]: unknown;
            };
            /**
             * Format: date
             * @description Latest bar date used as input; always <= date (point-in-time proof, Constitution VII).
             */
            data_window_end: string;
        };
        RunDetail: components["schemas"]["Run"] & {
            signals: components["schemas"]["ExperimentSignal"][];
        };
        EquityPoint: {
            /** Format: date */
            date: string;
            /** @description Book value on that date, in units of initial_capital. */
            value: number;
        };
        Trade: {
            symbol: string;
            /** Format: date */
            entry_date: string;
            entry_price: number;
            /**
             * Format: date
             * @description Null while the position is still open at the end of the window.
             */
            exit_date: string | null;
            /** @description Realised exit for a closed trade; the last close for an open one. */
            exit_price: number;
            return_pct: number;
            /** @description True when the position was still held at the end of the window. An open trade is marked to market, not realised, and never counts toward the win rate. */
            open: boolean;
        };
        PerformanceMetrics: {
            /** @description Fraction, e.g. 0.12 for +12%. */
            total_return: number;
            /** @description Annualised from daily returns at a zero risk-free rate. Null when undefined -- fewer than two points, or zero variance. A fabricated 0.0 would read as "measured, and mediocre". */
            sharpe_ratio: number | null;
            /** @description Negative fraction, e.g. -0.153 for a 15.3% peak-to-trough fall. Exactly 0 for a curve that never fell. */
            max_drawdown: number;
            /** @description Share of *closed* trades that gained. Null when nothing has closed. */
            win_rate: number | null;
            /** @description All positions, including any still open. */
            trade_count: number;
            winning_trades: number;
            losing_trades: number;
        };
        RunPerformance: {
            run_id: string;
            /** @description Notional book size. Arbitrary but fixed: every ratio reported here is scale-invariant, so this only sets the axis labels. */
            initial_capital: number;
            /** @description The strategy's book, marked to close on each bar date in the window. Empty when the window contained no bars. */
            equity: components["schemas"]["EquityPoint"][];
            /** @description Equal-weight buy-and-hold of the same selection. Deliberately the run's own universe rather than an index, so the comparison isolates the model's timing from which names it was pointed at. */
            benchmark: components["schemas"]["EquityPoint"][];
            metrics: components["schemas"]["PerformanceMetrics"];
            trades: components["schemas"]["Trade"][];
            /** @description Every simplification applied. These figures are not tradeable and must never be presented as if they were. */
            assumptions: string[];
        };
        /** @description The terminal event of a run's replay. Metrics are computed by the same helpers behind GET /runs/{run_id}/performance, over the replayed equity curve and trade list, so the two reconcile on the same run. */
        ReplaySummary: {
            run_id: string;
            /** @description Trading dates replayed (dates with at least one bar). */
            days: number;
            initial_cash: number;
            /** @description Book value on the last replayed date. */
            final_equity: number;
            /** @description Fraction, e.g. 0.12 for +12%. */
            total_return: number;
            /** @description Null when undefined -- fewer than two points, or zero variance. */
            sharpe_ratio: number | null;
            /** @description Negative fraction, peak to trough. */
            max_drawdown: number;
            /** @description Share of closed trades that gained. Null when nothing closed. */
            win_rate: number | null;
            /** @description All positions, including any still open. */
            trade_count: number;
            winning_trades: number;
            losing_trades: number;
            /** @description Every simplification applied, shared with the performance report. These figures are not tradeable and must never be presented as if they were. */
            assumptions: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backend is up and the seeded database is reachable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listInstruments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All seeded instruments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentList"];
                };
            };
        };
    };
    getPrices: {
        parameters: {
            query?: {
                start_date?: string;
                end_date?: string;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bars ordered ascending by date */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceBarList"];
                };
            };
            /** @description Unknown symbol */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listInstrumentFundamentalConcepts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Concept groups, ordered by concept, provider */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundamentalConceptList"];
                };
            };
            /** @description Unknown symbol */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getFundamentalSeries: {
        parameters: {
            query: {
                /** @description Canonical or derived concept, e.g. revenue or short_volume_ratio. */
                concept: string;
                transform?: "raw" | "raw_facts" | "yoy_growth";
                /** @description First filed_at to include (YYYY-MM-DD). */
                start_date?: string;
                /** @description Last filed_at to include (YYYY-MM-DD). */
                end_date?: string;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The transformed series */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundamentalSeries"];
                };
            };
            /** @description start_date after end_date */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unknown symbol */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listSignals: {
        parameters: {
            query?: {
                instrument?: string;
                /** @description Signal rule name, e.g. sma-crossover */
                signal_type?: string;
                direction?: components["schemas"]["Direction"];
                start_date?: string;
                end_date?: string;
                sort?: "date_asc" | "date_desc";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Filtered signals with total count */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalList"];
                };
            };
            /** @description Invalid filter combination (e.g. start_date after end_date) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered models */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelList"];
                };
            };
        };
    };
    listRuns: {
        parameters: {
            query?: {
                /** @description When true, return only runs saved with a name. */
                saved_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recorded runs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunList"];
                };
            };
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Run completed (a run producing zero signals is a success) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Unknown model, unknown custom_rule_id (including one owned by another user), or an unknown symbol in the selection */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Both or neither model selector sent, parameter outside its declared range, window shorter than the model's lookback, start_date after end_date, a selection larger than the permitted bound, or a template whose declared inputs the active dataset cannot serve (fundamentals on the synthetic demo). The offending field is named. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Unknown run */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown run */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    saveRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Updated run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Unknown run */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getRunPerformance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Performance of the run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPerformance"];
                };
            };
            /** @description Unknown run */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The run failed, so it has no performance. Zeroed figures would read as a flat book rather than as an absent result. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    streamRunReplay: {
        parameters: {
            query?: {
                /** @description Optional server-side pacing: milliseconds to wait between dates (after each equity event). 0 streams as fast as possible; the data is historical, so clients may pace themselves instead. */
                interval_ms?: number;
                /** @description Safety cap on frames emitted. On reaching it the stream ends with a `truncated` frame instead of `summary`. */
                max_events?: number;
                /** @description Emit bar events only every Nth date; 1 is every date. */
                step?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent event stream of replay events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Unknown run */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The run failed, so there is nothing to replay */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getRunReplaySummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Replay summary for the run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplaySummary"];
                };
            };
            /** @description Unknown run */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The run failed, so there is nothing to replay */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    streamLiveReplay: {
        parameters: {
            query: {
                /** @description Signal rule name; the latest registered version is used. */
                model?: string;
                /** @description Comma-separated canonical symbols, e.g. `ZX1.US,ZX2.US`. */
                symbols: string;
                /** @description First session date of the replayed window. */
                start: string;
                /** @description Last session date of the replayed window. */
                end: string;
                /** @description Model parameter overrides as a JSON object, e.g. `{"fast": 10, "slow": 30}`. */
                params?: string;
                /** @description Starting book value, split into equal per-symbol sleeves. */
                initial_cash?: number;
                /** @description Safety cap on frames emitted. On reaching it the stream ends with a `truncated` frame instead of `summary`. */
                max_events?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent event stream of replay events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Missing or malformed symbols, start, end or params */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unknown model */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A parameter override failed the model's declared spec */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The event bus is unconfigured or unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listSignalTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered templates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalTemplateList"];
                };
            };
        };
    };
    listCustomRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rules owned by the caller plus unscoped ones */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomRuleList"];
                };
            };
        };
    };
    createCustomRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomRuleRequest"];
            };
        };
        responses: {
            /** @description Rule created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomRule"];
                };
            };
            /** @description Unknown template */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Config failed the template's declared validation */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCustomRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The rule */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomRule"];
                };
            };
            /** @description Unknown rule, or one owned by another user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteCustomRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown rule, or one owned by another user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateCustomRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomRuleUpdateRequest"];
            };
        };
        responses: {
            /** @description Updated rule */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomRule"];
                };
            };
            /** @description Unknown rule, or one owned by another user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Empty patch, or config failed template validation */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthCredentials"];
            };
        };
        responses: {
            /** @description User created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Users exist and the caller has no session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Users exist and the caller is not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Username already taken (comparison is case-insensitive) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Username or password outside its declared bounds */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthCredentials"];
            };
        };
        responses: {
            /** @description Logged in; the session cookie is set */
            200: {
                headers: {
                    /** @description `quantlab_session=<token>; HttpOnly; SameSite=Lax; Path=/; Max-Age=1209600` (`Secure` only behind QUANTLAB_AUTH_COOKIE_SECURE) */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Invalid username or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Username or password outside its declared bounds */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Too many failed attempts from this client IP */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session deleted; the cookie is cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's identity */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description No valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
