/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service health, including seed status */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the synthetic instrument universe */
        get: operations["listInstruments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{symbol}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily OHLCV history for one instrument */
        get: operations["getPrices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List signals with filtering, sorting, and total count
         * @description `total` always reflects the full result set under the active filters, independent of pagination, so the UI count can be checked against the backend (SC-004).
         */
        get: operations["listSignals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok";
            /** @description True once the seed step has completed */
            seeded: boolean;
            signal_count: number;
        };
        /** @enum {string} */
        Direction: "bullish" | "bearish";
        Instrument: {
            /** @example ZZTRND */
            symbol: string;
            /** @example Zeno Trend Industries (synthetic) */
            name: string;
            /** @example USD */
            currency: string;
            /** @enum {string} */
            regime_profile: "trending" | "mean_reverting" | "volatile" | "mixed";
        };
        InstrumentList: {
            total: number;
            items: components["schemas"]["Instrument"][];
        };
        PriceBar: {
            symbol: string;
            /** Format: date */
            date: string;
            open: number;
            high: number;
            low: number;
            close: number;
            volume: number;
        };
        PriceBarList: {
            total: number;
            items: components["schemas"]["PriceBar"][];
        };
        Signal: {
            id: number;
            symbol: string;
            /**
             * Format: date
             * @description Signal date T; only data knowable by T was used
             */
            date: string;
            /** @example sma-crossover */
            rule_name: string;
            /** @example 1.0.0 */
            rule_version: string;
            /**
             * @example {
             *       "fast": 20,
             *       "slow": 50
             *     }
             */
            parameters: {
                [key: string]: unknown;
            };
            direction: components["schemas"]["Direction"];
            /**
             * @description Indicator values that fired the rule
             * @example {
             *       "sma_fast": 101.2,
             *       "sma_slow": 99.8
             *     }
             */
            trigger_values: {
                [key: string]: unknown;
            };
            /**
             * Format: date
             * @description Latest bar date used as input; always <= date (Constitution VII)
             */
            data_window_end: string;
        };
        SignalList: {
            /** @description Total signals matching the active filters (pre-pagination) */
            total: number;
            items: components["schemas"]["Signal"][];
        };
        Error: {
            detail: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backend is up and the seeded database is reachable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listInstruments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All seeded instruments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentList"];
                };
            };
        };
    };
    getPrices: {
        parameters: {
            query?: {
                start_date?: string;
                end_date?: string;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bars ordered ascending by date */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceBarList"];
                };
            };
            /** @description Unknown symbol */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listSignals: {
        parameters: {
            query?: {
                instrument?: string;
                /** @description Signal rule name, e.g. sma-crossover */
                signal_type?: string;
                direction?: components["schemas"]["Direction"];
                start_date?: string;
                end_date?: string;
                sort?: "date_asc" | "date_desc";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Filtered signals with total count */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalList"];
                };
            };
            /** @description Invalid filter combination (e.g. start_date after end_date) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
